name: VS Code CI/CD

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: echo "Test OK"
      - run: echo "Build OK"
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .